[project]
id = "wcm-local"

[api]
port = 3001
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
major_version = 15

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:9999/callback"
